version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./html:/usr/share/nginx/html
            - ./template:/etc/nginx/template
            - ./nginx.conf/etc/nginx/nginx.conf
        environment:
            DOMAIN: ${DOMAIN}
        labels:
            - ssl_nginx
        restart: always

    acme.sh:
        image: neilpang/acme.sh:latest
        depends_on:
            - nginx
        volumes:
            - ./entry.sh:/entry.sh
            - acme-data:/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            ['daemon']
        environment:
            - DOMAIN=${DOMAIN}
            - DEPLOY_DOCKER_CONTAINER_LABEL=ssl_nginx
            - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/${DOMAIN}.key
            - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE=/etc/nginx/ssl/${DOMAIN}.fullchain
            - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="envsubst '\$$DOMAIN' < /etc/nginx/template/shadowsocks.template > /etc/nginx/conf.d/shadowsocks.conf && nginx -s reload"
        restart: always

    shadowsocks:
        image: 455180748/ss-with-v2ray:latest
        container_name: ss-with-v2ray
        environment:
            PLUGIN_OPT: server;loglevel=error
            PASSWORD: ${PASSWORD}
        restart: always


volumes:
    acme-data:
